# Generated by Django 5.0.2 on 2024-02-23 12:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="helpr_id",
            name="calculation",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="customer",
            name="image",
            field=models.ImageField(blank=True, upload_to="uploads/product/"),
        ),
    ]
