# Generated by Django 5.0.2 on 2024-02-23 13:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0002_helpr_id_calculation_alter_customer_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="test",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("test1", models.CharField(max_length=50)),
            ],
        ),
    ]
