# Generated by Django 5.0.2 on 2024-02-28 11:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0003_test"),
    ]

    operations = [
        migrations.AddField(
            model_name="test",
            name="test_date_fra",
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AddField(
            model_name="test",
            name="test_date_til",
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
