# Generated by Django 5.0.2 on 2024-03-01 12:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0004_test_test_date_fra_test_test_date_til"),
    ]

    operations = [
        migrations.AddField(
            model_name="test",
            name="udregning_db",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
