# Generated by Django 5.0.2 on 2024-03-05 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0006_hangman"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hangman_category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("word", models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name="hangman",
            name="word",
        ),
        migrations.AddField(
            model_name="hangman",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="store.hangman_category",
            ),
        ),
    ]
