# Generated by Django 5.0.2 on 2024-03-05 12:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0007_hangman_category_remove_hangman_word_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hangman",
            name="guess",
            field=models.CharField(max_length=1, unique=True),
        ),
    ]
