# Generated by Django 5.0.2 on 2024-03-08 10:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0008_alter_hangman_guess"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hangman",
            name="category",
        ),
    ]
