# Generated by Django 5.0.2 on 2024-03-12 11:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0009_remove_hangman_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="test",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
