# Generated by Django 5.0.2 on 2024-03-20 11:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0014_remove_team_user_team_user_in_team_alter_team_leder"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="team",
            name="user_in_team",
        ),
        migrations.AddField(
            model_name="team",
            name="medlemmer",
            field=models.ManyToManyField(
                related_name="teams", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
