# Generated by Django 5.0.2 on 2024-03-20 12:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0015_remove_team_user_in_team_team_medlemmer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stats",
            name="user",
        ),
    ]
