# Generated by Django 5.0.2 on 2024-04-05 11:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0017_stats_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="stats",
            name="ga_2",
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="stats",
            name="ga_3",
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="stats",
            name="kontakttilladelser_2",
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="stats",
            name="kontakttilladelser_3",
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="stats",
            name="kpt_2",
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="stats",
            name="kpt_3",
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
    ]
