# Generated by Django 5.0.2 on 2024-04-09 10:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0018_stats_ga_2_stats_ga_3_stats_kontakttilladelser_2_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stats",
            name="trin_1",
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="stats",
            name="trin_2",
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="stats",
            name="trin_3",
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
    ]
