# Generated by Django 5.0.2 on 2024-04-18 11:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0022_rename_link_1_link_link_remove_link_link_2_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="link",
            old_name="link",
            new_name="link_1",
        ),
        migrations.AddField(
            model_name="link",
            name="link_2",
            field=models.CharField(default=1, max_length=70),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="link",
            name="link_3",
            field=models.CharField(default=1, max_length=70),
            preserve_default=False,
        ),
    ]
