# Generated by Django 5.0.2 on 2024-04-18 12:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0023_rename_link_link_link_1_link_link_2_link_link_3"),
    ]

    operations = [
        migrations.RenameField(
            model_name="link",
            old_name="link_1",
            new_name="facebook",
        ),
        migrations.RenameField(
            model_name="link",
            old_name="link_2",
            new_name="google",
        ),
        migrations.RenameField(
            model_name="link",
            old_name="link_3",
            new_name="twitter",
        ),
    ]
