# Generated by Django 5.0.2 on 2024-04-18 12:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0024_rename_link_1_link_facebook_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="link",
            old_name="facebook",
            new_name="link",
        ),
        migrations.RemoveField(
            model_name="link",
            name="google",
        ),
        migrations.RemoveField(
            model_name="link",
            name="twitter",
        ),
        migrations.AddField(
            model_name="link",
            name="name",
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
