# Generated by Django 5.0.2 on 2024-05-17 13:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0027_post_post_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="post_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
